INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10001, 'Francis', 'Thika', now());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10002, 'Ivan', 'Eldoret', now());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10003, 'Bowen', 'Nakuru', now());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10004, 'Eileen', 'Kakamega', now());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10005, 'Daisy', 'Nairobi', now());

select * from person;